In [1]:
import numpy as np

In [2]:
a = np.array([[1],
              [2],
              [3]])
print(a.shape)
a

(3, 1)


array([[1],
       [2],
       [3]])

In [3]:
my_list = np.array([4,5,6])
print(my_list.shape)
my_list

(3,)


array([4, 5, 6])

In [5]:
b = my_list.reshape(3,1)
print(b.shape)
b

(3, 1)


array([[4],
       [5],
       [6]])

# Vector Operations

In [8]:
a + b

array([[5],
       [7],
       [9]])

In [7]:
np.add(a,b)

array([[5],
       [7],
       [9]])

In [9]:
a+7

array([[ 8],
       [ 9],
       [10]])

In [10]:
alpha = 9
alpha * a

array([[ 9],
       [18],
       [27]])

# Matrix